version: '3.1'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "80:5000"
    secrets:
     - google_credentials

secrets:
  google_credentials:
    file: google_credentials.json
