version: '3.1'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    secrets:
     - google_credentials

secrets:
  google_credentials:
    file: ./client_secret.json